//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMC_Lite.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public ushort Steering_Wheel_Rotation_Range {
            get {
                return ((ushort)(this["Steering_Wheel_Rotation_Range"]));
            }
            set {
                this["Steering_Wheel_Rotation_Range"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public ushort Encoder_Pulse {
            get {
                return ((ushort)(this["Encoder_Pulse"]));
            }
            set {
                this["Encoder_Pulse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4095")]
        public ushort Accelerator_Pedal_Maximum {
            get {
                return ((ushort)(this["Accelerator_Pedal_Maximum"]));
            }
            set {
                this["Accelerator_Pedal_Maximum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort Accelerator_Pedal_Minimum {
            get {
                return ((ushort)(this["Accelerator_Pedal_Minimum"]));
            }
            set {
                this["Accelerator_Pedal_Minimum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4095")]
        public ushort Brake_Pedal_Maximum {
            get {
                return ((ushort)(this["Brake_Pedal_Maximum"]));
            }
            set {
                this["Brake_Pedal_Maximum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort Brake_Pedal_Minimum {
            get {
                return ((ushort)(this["Brake_Pedal_Minimum"]));
            }
            set {
                this["Brake_Pedal_Minimum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4095")]
        public ushort Clutch_Pedal_Maximum {
            get {
                return ((ushort)(this["Clutch_Pedal_Maximum"]));
            }
            set {
                this["Clutch_Pedal_Maximum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public ushort Effect_Gain_Controller_Spring_Gain {
            get {
                return ((ushort)(this["Effect_Gain_Controller_Spring_Gain"]));
            }
            set {
                this["Effect_Gain_Controller_Spring_Gain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public ushort Effect_Gain_Controller_Damper_Gain {
            get {
                return ((ushort)(this["Effect_Gain_Controller_Damper_Gain"]));
            }
            set {
                this["Effect_Gain_Controller_Damper_Gain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public ushort Effect_Gain_Controller_Friction_Gain {
            get {
                return ((ushort)(this["Effect_Gain_Controller_Friction_Gain"]));
            }
            set {
                this["Effect_Gain_Controller_Friction_Gain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public ushort Effect_Gain_Controller_Inertia_Gain {
            get {
                return ((ushort)(this["Effect_Gain_Controller_Inertia_Gain"]));
            }
            set {
                this["Effect_Gain_Controller_Inertia_Gain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public float Effect_Limiter_Inertia_Limiter {
            get {
                return ((float)(this["Effect_Limiter_Inertia_Limiter"]));
            }
            set {
                this["Effect_Limiter_Inertia_Limiter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public float Effect_Spring_PID_Kp {
            get {
                return ((float)(this["Effect_Spring_PID_Kp"]));
            }
            set {
                this["Effect_Spring_PID_Kp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public float Effect_Spring_PID_Ki {
            get {
                return ((float)(this["Effect_Spring_PID_Ki"]));
            }
            set {
                this["Effect_Spring_PID_Ki"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float Effect_Spring_PID_Kd {
            get {
                return ((float)(this["Effect_Spring_PID_Kd"]));
            }
            set {
                this["Effect_Spring_PID_Kd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public float Steering_Wheel_Software_Limiter_Kp {
            get {
                return ((float)(this["Steering_Wheel_Software_Limiter_Kp"]));
            }
            set {
                this["Steering_Wheel_Software_Limiter_Kp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float Steering_Wheel_Software_Limiter_Ki {
            get {
                return ((float)(this["Steering_Wheel_Software_Limiter_Ki"]));
            }
            set {
                this["Steering_Wheel_Software_Limiter_Ki"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float Steering_Wheel_Software_Limiter_Kd {
            get {
                return ((float)(this["Steering_Wheel_Software_Limiter_Kd"]));
            }
            set {
                this["Steering_Wheel_Software_Limiter_Kd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float PWM_Gain_Multiple_Value {
            get {
                return ((float)(this["PWM_Gain_Multiple_Value"]));
            }
            set {
                this["PWM_Gain_Multiple_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort Clutch_Pedal_Minimum {
            get {
                return ((ushort)(this["Clutch_Pedal_Minimum"]));
            }
            set {
                this["Clutch_Pedal_Minimum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public byte Led_Brightness {
            get {
                return ((byte)(this["Led_Brightness"]));
            }
            set {
                this["Led_Brightness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Led_Mode {
            get {
                return ((int)(this["Led_Mode"]));
            }
            set {
                this["Led_Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Led_Game_Mode {
            get {
                return ((bool)(this["Led_Game_Mode"]));
            }
            set {
                this["Led_Game_Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000000")]
        public string Led_Color_Mode_Color_String {
            get {
                return ((string)(this["Led_Color_Mode_Color_String"]));
            }
            set {
                this["Led_Color_Mode_Color_String"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort Joystick_1_Deadzone {
            get {
                return ((ushort)(this["Joystick_1_Deadzone"]));
            }
            set {
                this["Joystick_1_Deadzone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort Joystick_2_Deadzone {
            get {
                return ((ushort)(this["Joystick_2_Deadzone"]));
            }
            set {
                this["Joystick_2_Deadzone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32767")]
        public ushort Joystick_1_MaxValue {
            get {
                return ((ushort)(this["Joystick_1_MaxValue"]));
            }
            set {
                this["Joystick_1_MaxValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32767")]
        public ushort Joystick_2_MaxValue {
            get {
                return ((ushort)(this["Joystick_2_MaxValue"]));
            }
            set {
                this["Joystick_2_MaxValue"] = value;
            }
        }
    }
}
